# Generated by Django 4.1 on 2022-09-12 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_codigo', models.BigIntegerField()),
                ('model_nome', models.CharField(max_length=255)),
                ('model_texto', models.TextField()),
                ('model_tipo', models.CharField(max_length=1)),
                ('model_data_atualizacao', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 19, 34, 5, 855839))),
            ],
        ),
    ]
