# Generated by Django 4.1 on 2022-09-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('apl_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('apl_nome', models.CharField(max_length=50)),
                ('apl_versao', models.CharField(max_length=10)),
                ('apl_link_download', models.CharField(max_length=255)),
                ('apl_link_imagem', models.CharField(max_length=255)),
                ('apl_disponivel_download', models.CharField(max_length=1)),
                ('apl_projeto', models.CharField(max_length=125)),
                ('apl_data_lancamento', models.DateField()),
            ],
        ),
    ]
