# Generated by Django 4.1 on 2022-09-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('timestamp', models.BigIntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
