# Generated by Django 4.1 on 2022-09-05 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_log', models.BigIntegerField()),
                ('log_data', models.DateTimeField(default=datetime.datetime(2022, 9, 5, 9, 19, 19, 980895))),
                ('log_rotina', models.CharField(max_length=255)),
                ('log_retorno', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('auth_codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=255)),
                ('auth_provider', models.CharField(max_length=255)),
                ('auth_scope', models.CharField(max_length=255)),
                ('auth_application_id', models.CharField(max_length=255)),
                ('auth_application_secret', models.CharField(max_length=255)),
                ('auth_redirects_uri', models.TextField()),
                ('auth_client_uri', models.CharField(max_length=255)),
                ('auth_allowed_grant_types', models.TextField()),
                ('auth_allowed_response_types', models.TextField()),
                ('auth_token_ednpoint_auth_method', models.CharField(max_length=255)),
                ('auth_options', models.TextField()),
            ],
        ),
    ]
